# Generated by Django 4.2.23 on 2025-09-29 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CachedVideo',
        ),
    ]
